# Generated by Django 6.0.1 on 2026-01-24 15:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capteur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Poids', 'Poids'), ('Temperature', 'Temperature'), ('Humidite', 'Humidite')], max_length=20)),
                ('identifiant', models.CharField(max_length=100, unique=True)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cheptel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anneeNaissance', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('codeCouleur', models.CharField(max_length=20)),
                ('lignee', models.CharField(max_length=100)),
                ('noteDouceur', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('commentaire', models.TextField(blank=True)),
                ('nonReproductible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('flore', models.CharField(choices=[('Acacia', 'Acacia'), ('Colza', 'Colza'), ('Lavande', 'Lavande'), ('Tournesol', 'Tournesol'), ('Chataignier', 'Chataignier'), ('Bruyere', 'Bruyere'), ('Montagne', 'Montagne'), ('ToutesFleurs', 'ToutesFleurs')], max_length=20)),
                ('altitude', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TraceurGPS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifiant', models.CharField(max_length=100, unique=True)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('motDePasseHash', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Apiculteur', 'Apiculteur'), ('Lecteur', 'Lecteur')], default='Lecteur', max_length=20)),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('valeur', models.FloatField()),
                ('capteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures', to='core.capteur')),
            ],
        ),
        migrations.CreateModel(
            name='Ruche',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('immatriculation', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('race', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('Active', 'Active'), ('Malade', 'Malade'), ('Morte', 'Morte')], default='Active', max_length=20)),
                ('securisee', models.BooleanField(default=False)),
                ('cheptel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruches', to='core.cheptel')),
                ('reine', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ruche', to='core.reine')),
                ('traceur_gps', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ruche', to='core.traceurgps')),
            ],
        ),
        migrations.CreateModel(
            name='Recolte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('nbHausses', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('poidsKg', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('notes', models.TextField(blank=True)),
                ('ruche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoltes', to='core.ruche')),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Visite', 'Visite'), ('Nourrissement', 'Nourrissement'), ('Traitement', 'Traitement'), ('Recolte', 'Recolte')], max_length=20)),
                ('date', models.DateField()),
                ('observations', models.TextField(blank=True)),
                ('ruche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='core.ruche')),
            ],
        ),
        migrations.AddField(
            model_name='capteur',
            name='ruche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capteurs', to='core.ruche'),
        ),
        migrations.AddField(
            model_name='cheptel',
            name='rucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheptels', to='core.rucher'),
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('acquittee', models.BooleanField(default=False)),
                ('traceur_gps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='core.traceurgps')),
            ],
        ),
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('produit', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('dosage', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('ruche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traitements', to='core.ruche')),
            ],
        ),
        migrations.CreateModel(
            name='Transhumance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('origineLat', models.FloatField()),
                ('origineLng', models.FloatField()),
                ('destinationLat', models.FloatField()),
                ('destinationLng', models.FloatField()),
                ('floreCible', models.CharField(choices=[('Acacia', 'Acacia'), ('Colza', 'Colza'), ('Lavande', 'Lavande'), ('Tournesol', 'Tournesol'), ('Chataignier', 'Chataignier'), ('Bruyere', 'Bruyere'), ('Montagne', 'Montagne'), ('ToutesFleurs', 'ToutesFleurs')], max_length=20)),
                ('cheptel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transhumances', to='core.cheptel')),
            ],
        ),
        migrations.AddField(
            model_name='rucher',
            name='possesseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruchers', to='core.utilisateur'),
        ),
    ]
