-- Remove UUID defaults (revert)

ALTER TABLE interventions ALTER COLUMN id DROP DEFAULT;
ALTER TABLE alertes ALTER COLUMN id DROP DEFAULT;
ALTER TABLE transhumances ALTER COLUMN id DROP DEFAULT;
ALTER TABLE mesures ALTER COLUMN id DROP DEFAULT;
ALTER TABLE capteurs ALTER COLUMN id DROP DEFAULT;
ALTER TABLE reines ALTER COLUMN id DROP DEFAULT;
ALTER TABLE ruches ALTER COLUMN id DROP DEFAULT;
ALTER TABLE ruchers ALTER COLUMN id DROP DEFAULT;
ALTER TABLE offres ALTER COLUMN id DROP DEFAULT;
ALTER TABLE invitations ALTER COLUMN id DROP DEFAULT;
ALTER TABLE utilisateurs_entreprises ALTER COLUMN id DROP DEFAULT;
ALTER TABLE entreprises ALTER COLUMN id DROP DEFAULT;
ALTER TABLE utilisateurs ALTER COLUMN id DROP DEFAULT;
