# Generated by Django 5.0 on 2026-02-02 13:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capteur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Poids', 'Poids'), ('Temperature', 'Temperature'), ('Humidite', 'Humidite'), ('GPS', 'GPS'), ('CO2', 'CO2'), ('Son', 'Son'), ('Batterie', 'Batterie')], max_length=20)),
                ('identifiant', models.CharField(max_length=100, unique=True)),
                ('actif', models.BooleanField(default=True)),
                ('batteriePct', models.FloatField(blank=True, null=True)),
                ('derniereCommunication', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Capteur',
                'verbose_name_plural': 'Capteurs',
                'db_table': 'capteurs',
            },
        ),
        migrations.CreateModel(
            name='Reine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anneeNaissance', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('codeCouleur', models.CharField(max_length=20)),
                ('lignee', models.CharField(max_length=100)),
                ('noteDouceur', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('commentaire', models.TextField(blank=True)),
                ('nonReproductible', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Reine',
                'verbose_name_plural': 'Reines',
                'db_table': 'reines',
            },
        ),
        migrations.CreateModel(
            name='Rucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('flore', models.CharField(choices=[('Acacia', 'Acacia'), ('Colza', 'Colza'), ('Lavande', 'Lavande'), ('Tournesol', 'Tournesol'), ('Chataignier', 'Chataignier'), ('Bruyere', 'Bruyere'), ('Montagne', 'Montagne'), ('ToutesFleurs', 'ToutesFleurs')], max_length=20)),
                ('altitude', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Rucher',
                'verbose_name_plural': 'Ruchers',
                'db_table': 'ruchers',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('motDePasseHash', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Apiculteur', 'Apiculteur'), ('Lecteur', 'Lecteur')], default='Lecteur', max_length=20)),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Vol', 'Vol'), ('ChutePoids', 'ChutePoids'), ('TemperatureCritique', 'TemperatureCritique'), ('BatterieFaible', 'BatterieFaible'), ('DeplacementGPS', 'DeplacementGPS'), ('HorsLigne', 'HorsLigne')], max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('acquittee', models.BooleanField(default=False)),
                ('capteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='core.capteur')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'db_table': 'alertes',
            },
        ),
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('valeur', models.FloatField()),
                ('capteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures', to='core.capteur')),
            ],
            options={
                'verbose_name': 'Mesure',
                'verbose_name_plural': 'Mesures',
                'db_table': 'mesures',
            },
        ),
        migrations.CreateModel(
            name='Ruche',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('immatriculation', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('race', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('Active', 'Active'), ('Faible', 'Faible'), ('Malade', 'Malade'), ('Morte', 'Morte')], default='Active', max_length=20)),
                ('securisee', models.BooleanField(default=False)),
                ('reine', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ruche', to='core.reine')),
                ('rucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruches', to='core.rucher')),
            ],
            options={
                'verbose_name': 'Ruche',
                'verbose_name_plural': 'Ruches',
                'db_table': 'ruches',
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Visite', 'Visite'), ('Nourrissement', 'Nourrissement'), ('Traitement', 'Traitement'), ('Recolte', 'Recolte'), ('Division', 'Division'), ('PoseHausse', 'PoseHausse'), ('ControleSanitaire', 'ControleSanitaire')], max_length=30)),
                ('date', models.DateField()),
                ('observations', models.TextField(blank=True)),
                ('produit', models.CharField(blank=True, max_length=200)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('nbHausses', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('poidsKg', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('ruche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='core.ruche')),
            ],
            options={
                'verbose_name': 'Intervention',
                'verbose_name_plural': 'Interventions',
                'db_table': 'interventions',
            },
        ),
        migrations.AddField(
            model_name='capteur',
            name='ruche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capteurs', to='core.ruche'),
        ),
        migrations.CreateModel(
            name='Transhumance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('origineLat', models.FloatField()),
                ('origineLng', models.FloatField()),
                ('destinationLat', models.FloatField()),
                ('destinationLng', models.FloatField()),
                ('floreCible', models.CharField(choices=[('Acacia', 'Acacia'), ('Colza', 'Colza'), ('Lavande', 'Lavande'), ('Tournesol', 'Tournesol'), ('Chataignier', 'Chataignier'), ('Bruyere', 'Bruyere'), ('Montagne', 'Montagne'), ('ToutesFleurs', 'ToutesFleurs')], max_length=20)),
                ('rucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transhumances', to='core.rucher')),
            ],
            options={
                'verbose_name': 'Transhumance',
                'verbose_name_plural': 'Transhumances',
                'db_table': 'transhumances',
            },
        ),
        migrations.AddField(
            model_name='rucher',
            name='possesseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruchers', to='core.utilisateur'),
        ),
    ]
