# Generated by Django 5.0 on 2026-02-02 16:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.TextField()),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'db_table': 'entreprises',
            },
        ),
        migrations.RemoveField(
            model_name='rucher',
            name='possesseur',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='role',
        ),
        migrations.AddField(
            model_name='rucher',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ruchers', to='core.entreprise'),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('rolePropose', models.CharField(choices=[('AdminEntreprise', 'AdminEntreprise'), ('Apiculteur', 'Apiculteur'), ('Lecteur', 'Lecteur')], max_length=20)),
                ('dateExpiration', models.DateTimeField()),
                ('dateEnvoi', models.DateTimeField(auto_now_add=True)),
                ('acceptee', models.BooleanField(default=False)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='core.entreprise')),
                ('envoyeePar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_envoyees', to='core.utilisateur')),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
                'db_table': 'invitations',
            },
        ),
        migrations.CreateModel(
            name='UtilisateurEntreprise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('AdminEntreprise', 'AdminEntreprise'), ('Apiculteur', 'Apiculteur'), ('Lecteur', 'Lecteur')], max_length=20)),
                ('dateAjout', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='core.entreprise')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appartenances', to='core.utilisateur')),
            ],
            options={
                'verbose_name': 'UtilisateurEntreprise',
                'verbose_name_plural': 'UtilisateursEntreprises',
                'db_table': 'utilisateurs_entreprises',
                'unique_together': {('utilisateur', 'entreprise')},
            },
        ),
    ]
