# Generated by Django 5.0 on 2026-02-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_offre'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruche',
            name='maladie',
            field=models.CharField(choices=[('Aucune', 'Aucune'), ('Varroose', 'Varroose'), ('Nosemose', 'Nosemose'), ('LoqueAmericaine', 'LoqueAmericaine'), ('LoqueEuropeenne', 'LoqueEuropeenne'), ('Acarapisose', 'Acarapisose'), ('Ascospherose', 'Ascospherose'), ('Tropilaelaps', 'Tropilaelaps'), ('VirusAilesDeformees', 'VirusAilesDeformees'), ('ParalysieChronique', 'ParalysieChronique'), ('IntoxicationPesticides', 'IntoxicationPesticides')], default='Aucune', max_length=50),
        ),
    ]
