# Generated by Django 5.0 on 2026-02-03 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_maladie_ruche'),
    ]

    operations = [
        migrations.DeleteModel(
            name='__tmp__TypeMaladie',
        ),
    ]
