# Generated by Django 5.0 on 2026-02-03 14:35

from django.core.validators import RegexValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_ruche_maladie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ruche",
            name="immatriculation",
            field=models.CharField(
                max_length=50,
                unique=True,
                validators=[
                    RegexValidator(
                        regex="^A\\d{7}$",
                        message="L'immatriculation doit être au format A1234567.",
                    )
                ],
            ),
        ),
    ]
