# Generated by Django 5.0 on 2026-02-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_ruche_immatriculation_regex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ruche",
            name="type",
            field=models.CharField(
                max_length=20,
                choices=[
                    ("Dadant", "Dadant"),
                    ("Langstroth", "Langstroth"),
                    ("Warre", "Warre"),
                    ("Voirnot", "Voirnot"),
                    ("KenyaTopBar", "KenyaTopBar"),
                    ("Ruchette", "Ruchette"),
                    ("Nuclei", "Nuclei"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="ruche",
            name="race",
            field=models.CharField(
                max_length=20,
                choices=[
                    ("Buckfast", "Buckfast"),
                    ("Noire", "Noire"),
                    ("Carnica", "Carnica"),
                    ("Ligustica", "Ligustica"),
                    ("Caucasica", "Caucasica"),
                    ("HybrideLocale", "HybrideLocale"),
                    ("Inconnue", "Inconnue"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="reine",
            name="codeCouleur",
            field=models.CharField(
                max_length=10,
                choices=[
                    ("Blanc", "Blanc"),
                    ("Jaune", "Jaune"),
                    ("Rouge", "Rouge"),
                    ("Vert", "Vert"),
                    ("Bleu", "Bleu"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="reine",
            name="lignee",
            field=models.CharField(
                max_length=20,
                choices=[
                    ("Buckfast", "Buckfast"),
                    ("Carnica", "Carnica"),
                    ("Ligustica", "Ligustica"),
                    ("Caucasica", "Caucasica"),
                    ("Locale", "Locale"),
                    ("Inconnue", "Inconnue"),
                ],
            ),
        ),
    ]
