# Generated by Django 5.0 on 2026-02-03 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_ruche_reine_enums"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ruche",
            name="reine",
        ),
        migrations.AddField(
            model_name="reine",
            name="entreprise",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reines",
                to="core.entreprise",
            ),
        ),
        migrations.AddField(
            model_name="reine",
            name="ruche",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reine",
                to="core.ruche",
            ),
        ),
    ]
