# Generated by Codex on 2026-02-04

from django.db import migrations, models


def seed_enum_tables(apps, schema_editor):
    TypeFlore = apps.get_model("core", "TypeFlore")
    TypeRuche = apps.get_model("core", "TypeRuche")
    TypeRaceAbeille = apps.get_model("core", "TypeRaceAbeille")
    LigneeReine = apps.get_model("core", "LigneeReine")
    TypeMaladie = apps.get_model("core", "TypeMaladie")

    TypeFlore.objects.bulk_create(
        [
            TypeFlore(value="Acacia", label="Acacia"),
            TypeFlore(value="Colza", label="Colza"),
            TypeFlore(value="Lavande", label="Lavande"),
            TypeFlore(value="Tournesol", label="Tournesol"),
            TypeFlore(value="Chataignier", label="Chataignier"),
            TypeFlore(value="Bruyere", label="Bruyere"),
            TypeFlore(value="Montagne", label="Montagne"),
            TypeFlore(value="ToutesFleurs", label="ToutesFleurs"),
        ],
        ignore_conflicts=True,
    )

    TypeRuche.objects.bulk_create(
        [
            TypeRuche(value="Dadant", label="Dadant"),
            TypeRuche(value="Langstroth", label="Langstroth"),
            TypeRuche(value="Warre", label="Warre"),
            TypeRuche(value="Voirnot", label="Voirnot"),
            TypeRuche(value="KenyaTopBar", label="KenyaTopBar"),
            TypeRuche(value="Ruchette", label="Ruchette"),
            TypeRuche(value="Nuclei", label="Nuclei"),
        ],
        ignore_conflicts=True,
    )

    TypeRaceAbeille.objects.bulk_create(
        [
            TypeRaceAbeille(value="Buckfast", label="Buckfast"),
            TypeRaceAbeille(value="Noire", label="Noire"),
            TypeRaceAbeille(value="Carnica", label="Carnica"),
            TypeRaceAbeille(value="Ligustica", label="Ligustica"),
            TypeRaceAbeille(value="Caucasica", label="Caucasica"),
            TypeRaceAbeille(value="HybrideLocale", label="HybrideLocale"),
            TypeRaceAbeille(value="Inconnue", label="Inconnue"),
        ],
        ignore_conflicts=True,
    )

    LigneeReine.objects.bulk_create(
        [
            LigneeReine(value="Buckfast", label="Buckfast"),
            LigneeReine(value="Carnica", label="Carnica"),
            LigneeReine(value="Ligustica", label="Ligustica"),
            LigneeReine(value="Caucasica", label="Caucasica"),
            LigneeReine(value="Locale", label="Locale"),
            LigneeReine(value="Inconnue", label="Inconnue"),
        ],
        ignore_conflicts=True,
    )

    TypeMaladie.objects.bulk_create(
        [
            TypeMaladie(value="Aucune", label="Aucune"),
            TypeMaladie(value="Varroose", label="Varroose"),
            TypeMaladie(value="Nosemose", label="Nosemose"),
            TypeMaladie(value="LoqueAmericaine", label="LoqueAmericaine"),
            TypeMaladie(value="LoqueEuropeenne", label="LoqueEuropeenne"),
            TypeMaladie(value="Acarapisose", label="Acarapisose"),
            TypeMaladie(value="Ascospherose", label="Ascospherose"),
            TypeMaladie(value="Tropilaelaps", label="Tropilaelaps"),
            TypeMaladie(value="VirusAilesDeformees", label="VirusAilesDeformees"),
            TypeMaladie(value="ParalysieChronique", label="ParalysieChronique"),
            TypeMaladie(value="IntoxicationPesticides", label="IntoxicationPesticides"),
        ],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_timestamped_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeFlore",
            fields=[
                ("value", models.CharField(max_length=50, primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "type_flore",
                "verbose_name": "Type de flore",
                "verbose_name_plural": "Types de flore",
            },
        ),
        migrations.CreateModel(
            name="TypeRuche",
            fields=[
                ("value", models.CharField(max_length=50, primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "type_ruche",
                "verbose_name": "Type de ruche",
                "verbose_name_plural": "Types de ruche",
            },
        ),
        migrations.CreateModel(
            name="TypeRaceAbeille",
            fields=[
                ("value", models.CharField(max_length=50, primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "type_race_abeille",
                "verbose_name": "Type de race d'abeille",
                "verbose_name_plural": "Types de race d'abeille",
            },
        ),
        migrations.CreateModel(
            name="LigneeReine",
            fields=[
                ("value", models.CharField(max_length=50, primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "lignee_reine",
                "verbose_name": "Lignee de reine",
                "verbose_name_plural": "Lignees de reine",
            },
        ),
        migrations.CreateModel(
            name="TypeMaladie",
            fields=[
                ("value", models.CharField(max_length=50, primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "type_maladie",
                "verbose_name": "Type de maladie",
                "verbose_name_plural": "Types de maladie",
            },
        ),
        migrations.RunPython(seed_enum_tables, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="rucher",
            name="flore",
            field=models.ForeignKey(
                db_column="flore",
                on_delete=models.PROTECT,
                to="core.typeflore",
                to_field="value",
            ),
        ),
        migrations.AlterField(
            model_name="ruche",
            name="type",
            field=models.ForeignKey(
                db_column="type",
                on_delete=models.PROTECT,
                to="core.typeruche",
                to_field="value",
            ),
        ),
        migrations.AlterField(
            model_name="ruche",
            name="race",
            field=models.ForeignKey(
                db_column="race",
                on_delete=models.PROTECT,
                to="core.typeraceabeille",
                to_field="value",
            ),
        ),
        migrations.AlterField(
            model_name="ruche",
            name="maladie",
            field=models.ForeignKey(
                db_column="maladie",
                default="Aucune",
                on_delete=models.PROTECT,
                to="core.typemaladie",
                to_field="value",
            ),
        ),
        migrations.AlterField(
            model_name="reine",
            name="lignee",
            field=models.ForeignKey(
                db_column="lignee",
                on_delete=models.PROTECT,
                to="core.ligneereine",
                to_field="value",
            ),
        ),
        migrations.AlterField(
            model_name="transhumance",
            name="floreCible",
            field=models.ForeignKey(
                db_column="floreCible",
                on_delete=models.PROTECT,
                to="core.typeflore",
                to_field="value",
            ),
        ),
    ]
