# Generated by Django 5.0 on 2026-02-04 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_enum_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reine',
            name='lignee',
            field=models.ForeignKey(db_column='lignee', on_delete=django.db.models.deletion.PROTECT, to='core.ligneereine'),
        ),
        migrations.AlterField(
            model_name='ruche',
            name='maladie',
            field=models.ForeignKey(db_column='maladie', default='Aucune', on_delete=django.db.models.deletion.PROTECT, to='core.typemaladie'),
        ),
        migrations.AlterField(
            model_name='ruche',
            name='race',
            field=models.ForeignKey(db_column='race', on_delete=django.db.models.deletion.PROTECT, to='core.typeraceabeille'),
        ),
        migrations.AlterField(
            model_name='ruche',
            name='type',
            field=models.ForeignKey(db_column='type', on_delete=django.db.models.deletion.PROTECT, to='core.typeruche'),
        ),
        migrations.AlterField(
            model_name='rucher',
            name='flore',
            field=models.ForeignKey(db_column='flore', on_delete=django.db.models.deletion.PROTECT, to='core.typeflore'),
        ),
        migrations.AlterField(
            model_name='transhumance',
            name='floreCible',
            field=models.ForeignKey(db_column='floreCible', on_delete=django.db.models.deletion.PROTECT, to='core.typeflore'),
        ),
    ]
