# Generated by Django 5.0 on 2026-02-04 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_invitation_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='produit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='dosage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='nbHausses',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='poidsKg',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
