# Generated by Codex on 2026-02-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_invitation_token_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intervention",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
