# Generated by Django 5.0 on 2026-02-07 14:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_intervention_date_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitationOffre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('typeOffre', models.CharField(choices=[('Freemium', 'Freemium'), ('Premium', 'Premium')], max_length=20)),
                ('nbRuchersMax', models.IntegerField()),
                ('nbCapteursMax', models.IntegerField()),
                ('nbReinesMax', models.IntegerField()),
            ],
            options={
                'verbose_name': 'LimitationOffre',
                'verbose_name_plural': 'LimitationsOffres',
                'db_table': 'limitations_offres',
            },
        ),
        migrations.AddField(
            model_name='alerte',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mesure',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='offre',
            name='nbReinesMax',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offre',
            name='entreprise',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offre', to='core.entreprise'),
        ),
        migrations.CreateModel(
            name='EntrepriseProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('typeProfile', models.CharField(choices=[('ApiculteurProducteur', 'ApiculteurProducteur'), ('EleveurDeReines', 'EleveurDeReines'), ('Pollinisateur', 'Pollinisateur')], max_length=30)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profils', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'EntrepriseProfile',
                'verbose_name_plural': 'EntrepriseProfiles',
                'db_table': 'entreprise_profiles',
            },
        ),
        migrations.AddField(
            model_name='offre',
            name='limitationOffre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offres', to='core.limitationoffre'),
        ),
    ]
