# Generated by Codex on 2026-02-07

from django.db import migrations


def seed_limitation_offre(apps, schema_editor):
    LimitationOffre = apps.get_model("core", "LimitationOffre")

    def upsert(type_offre, nb_ruchers_max, nb_capteurs_max, nb_reines_max):
        updated = LimitationOffre.objects.filter(typeOffre=type_offre).update(
            nbRuchersMax=nb_ruchers_max,
            nbCapteursMax=nb_capteurs_max,
            nbReinesMax=nb_reines_max,
        )
        if not updated:
            LimitationOffre.objects.create(
                typeOffre=type_offre,
                nbRuchersMax=nb_ruchers_max,
                nbCapteursMax=nb_capteurs_max,
                nbReinesMax=nb_reines_max,
            )

    upsert("Freemium", 1, 0, 3)
    upsert("Premium", 50, 3, 100)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_limitationoffre_alerte_date_mesure_date_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_limitation_offre, migrations.RunPython.noop),
    ]
