# Generated by Codex on 2026-02-07

from django.db import migrations, models


def seed_type_offre(apps, schema_editor):
    TypeOffreModel = apps.get_model("core", "TypeOffreModel")

    TypeOffreModel.objects.update_or_create(
        value="Freemium",
        defaults={
            "titre": "Freemium",
            "description": "Offre decouverte avec limitations.",
        },
    )
    TypeOffreModel.objects.update_or_create(
        value="Premium",
        defaults={
            "titre": "Premium",
            "description": "Offre complete avec capacites etendues.",
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_seed_limitationoffre"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeOffreModel",
            fields=[
                ("value", models.CharField(max_length=20, primary_key=True, serialize=False)),
                ("titre", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "type_offre",
                "verbose_name": "Type d'offre",
                "verbose_name_plural": "Types d'offre",
            },
        ),
        migrations.RunPython(seed_type_offre, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="limitationoffre",
            name="typeOffre",
            field=models.ForeignKey(
                db_column="typeOffre",
                on_delete=models.PROTECT,
                to="core.typeoffremodel",
                to_field="value",
            ),
        ),
        migrations.AlterField(
            model_name="offre",
            name="type",
            field=models.ForeignKey(
                db_column="type",
                on_delete=models.PROTECT,
                to="core.typeoffremodel",
                to_field="value",
            ),
        ),
    ]
