# Generated by Codex on 2026-02-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_typeoffre_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="offre",
            name="stripeSubscriptionId",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
