# Generated by Django 5.0 on 2026-02-07 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_offre_stripe_subscription_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeProfileEntrepriseModel',
            fields=[
                ('value', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Type de profil entreprise',
                'verbose_name_plural': 'Types de profil entreprise',
                'db_table': 'type_profile_entreprise',
            },
        ),
        migrations.AddField(
            model_name='typeoffremodel',
            name='prixHT',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='typeoffremodel',
            name='prixTTC',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='typeoffremodel',
            name='stripeProductId',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='limitationoffre',
            name='typeOffre',
            field=models.ForeignKey(db_column='typeOffre', on_delete=django.db.models.deletion.PROTECT, to='core.typeoffremodel'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='type',
            field=models.ForeignKey(db_column='type', on_delete=django.db.models.deletion.PROTECT, to='core.typeoffremodel'),
        ),
        migrations.AlterField(
            model_name='entrepriseprofile',
            name='typeProfile',
            field=models.ForeignKey(db_column='typeProfile', on_delete=django.db.models.deletion.PROTECT, to='core.typeprofileentreprisemodel'),
        ),
    ]
