# Generated by Codex on 2026-02-07

from django.db import migrations


def seed_type_offre_pricing(apps, schema_editor):
    TypeOffreModel = apps.get_model("core", "TypeOffreModel")

    TypeOffreModel.objects.update_or_create(
        value="Freemium",
        defaults={
            "titre": "Freemium",
            "description": "Offre decouverte avec limitations.",
            "prixHT": 0,
            "prixTTC": 0,
            "stripeProductId": "",
        },
    )
    TypeOffreModel.objects.update_or_create(
        value="Premium",
        defaults={
            "titre": "Premium",
            "description": "Offre complete avec capacites etendues.",
            "prixHT": 3.60,
            "prixTTC": 3.60,
            "stripeProductId": "prod_Tw4zoKqamoCj4W",
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_typeprofileentreprisemodel_typeoffremodel_prixht_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_type_offre_pricing, migrations.RunPython.noop),
    ]
