# Generated by Codex on 2026-02-07

from django.db import migrations


def seed_type_profile_entreprise(apps, schema_editor):
    TypeProfileEntrepriseModel = apps.get_model("core", "TypeProfileEntrepriseModel")

    TypeProfileEntrepriseModel.objects.update_or_create(
        value="ApiculteurProducteur",
        defaults={
            "titre": "Apiculteur Producteur",
            "description": "",
        },
    )
    TypeProfileEntrepriseModel.objects.update_or_create(
        value="EleveurDeReines",
        defaults={
            "titre": "Eleveur de reines",
            "description": "",
        },
    )
    TypeProfileEntrepriseModel.objects.update_or_create(
        value="Pollinisateur",
        defaults={
            "titre": "Pollinisateur",
            "description": "",
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_seed_typeoffre_pricing"),
    ]

    operations = [
        migrations.RunPython(seed_type_profile_entreprise, migrations.RunPython.noop),
    ]
