# Generated by Codex on 2026-02-09

from django.core.validators import RegexValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_seed_typeprofile_entreprise"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ruche",
            name="immatriculation",
            field=models.CharField(
                max_length=50,
                unique=True,
                validators=[
                    RegexValidator(
                        regex=r"^[A-Z]\d{7}$",
                        message="L'immatriculation doit être au format X1234567.",
                    )
                ],
            ),
        ),
    ]
