# Generated by Django 5.0 on 2026-02-09 10:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_ruche_immatriculation_regex'),
    ]

    operations = [
        migrations.AddField(
            model_name='reine',
            name='isElevage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reine',
            name='statut',
            field=models.CharField(choices=[('Vendu', 'Vendu'), ('Perdue', 'Perdue'), ('NonFecondee', 'NonFecondee'), ('Fecondee', 'Fecondee'), ('DisponibleVente', 'DisponibleVente'), ('Eliminee', 'Eliminee')], default='Fecondee', max_length=30),
        ),
        migrations.CreateModel(
            name='CycleElevageReine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateDebut', models.DateField()),
                ('dateFin', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EnCours', 'EnCours'), ('Termine', 'Termine'), ('Annule', 'Annule')], default='EnCours', max_length=20)),
                ('reine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles_elevage', to='core.reine')),
            ],
            options={
                'verbose_name': "Cycle d'elevage de reine",
                'verbose_name_plural': "Cycles d'elevage de reine",
                'db_table': 'cycles_elevage_reines',
            },
        ),
        migrations.CreateModel(
            name='TacheCycleElevage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Greffage', 'Greffage'), ('Operculation', 'Operculation'), ('NaissanceReine', 'NaissanceReine'), ('ControleVolFecondation', 'ControleVolFecondation'), ('ValidationPonte', 'ValidationPonte'), ('MarquageReine', 'MarquageReine'), ('MiseEnVente', 'MiseEnVente')], max_length=40)),
                ('jourTheorique', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('datePrevue', models.DateField()),
                ('dateRealisee', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('AFaire', 'AFaire'), ('Faite', 'Faite'), ('EnRetard', 'EnRetard'), ('Annulee', 'Annulee')], default='AFaire', max_length=20)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='core.cycleelevagereine')),
            ],
            options={
                'verbose_name': "Tache de cycle d'elevage",
                'verbose_name_plural': "Taches de cycle d'elevage",
                'db_table': 'taches_cycle_elevage',
            },
        ),
    ]
