# Generated by Django 5.0 on 2026-02-09 15:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_reine_iselevage_reine_statut_cycleelevagereine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('RappelVisite', 'RappelVisite'), ('RappelTraitement', 'RappelTraitement'), ('Equipe', 'Equipe'), ('Saisonnier', 'Saisonnier'), ('AlerteSanitaire', 'AlerteSanitaire')], max_length=30)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lue', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.entreprise')),
                ('intervention', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.intervention')),
                ('ruche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.ruche')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.utilisateur')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['utilisateur', 'entreprise', '-date'], name='notificatio_utilisa_bfe040_idx'), models.Index(fields=['utilisateur', 'lue'], name='notificatio_utilisa_5b7b58_idx')],
            },
        ),
    ]
