# Generated by Django 5.0 on 2026-02-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_capteur_gps_alert_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('RappelVisite', 'RappelVisite'), ('RappelTraitement', 'RappelTraitement'), ('Equipe', 'Equipe'), ('Saisonnier', 'Saisonnier'), ('AlerteSanitaire', 'AlerteSanitaire'), ('AlerteGPS', 'AlerteGPS')], max_length=30),
        ),
    ]
