# Generated by Django 5.0 on 2026-02-10 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_notification_type'),
        ('core', '0027_account_verification_token'),
    ]

    operations = [
    ]
