# Generated by Django 5.0 on 2026-02-10 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_racleelevage_cycle_racle'),
        ('core', '0029_password_reset_token'),
    ]

    operations = [
    ]
